// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/minik8s.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PodSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"` // на будущее: контейнер, но пока обычный процесс
	Cmd           []string               `protobuf:"bytes,3,rep,name=cmd,proto3" json:"cmd,omitempty"`     // процесс для запуска на ноде
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodSpec) Reset() {
	*x = PodSpec{}
	mi := &file_proto_minik8s_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodSpec) ProtoMessage() {}

func (x *PodSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_minik8s_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodSpec.ProtoReflect.Descriptor instead.
func (*PodSpec) Descriptor() ([]byte, []int) {
	return file_proto_minik8s_proto_rawDescGZIP(), []int{0}
}

func (x *PodSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PodSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *PodSpec) GetCmd() []string {
	if x != nil {
		return x.Cmd
	}
	return nil
}

type Pod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Spec          *PodSpec               `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // Pending / Running / Failed / Succeeded
	NodeName      string                 `protobuf:"bytes,4,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pod) Reset() {
	*x = Pod{}
	mi := &file_proto_minik8s_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pod) ProtoMessage() {}

func (x *Pod) ProtoReflect() protoreflect.Message {
	mi := &file_proto_minik8s_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pod.ProtoReflect.Descriptor instead.
func (*Pod) Descriptor() ([]byte, []int) {
	return file_proto_minik8s_proto_rawDescGZIP(), []int{1}
}

func (x *Pod) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Pod) GetSpec() *PodSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Pod) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Pod) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CpuLoad       float64                `protobuf:"fixed64,2,opt,name=cpu_load,json=cpuLoad,proto3" json:"cpu_load,omitempty"`
	MemLoad       float64                `protobuf:"fixed64,3,opt,name=mem_load,json=memLoad,proto3" json:"mem_load,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // Ready / NotReady
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_proto_minik8s_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_proto_minik8s_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_proto_minik8s_proto_rawDescGZIP(), []int{2}
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetCpuLoad() float64 {
	if x != nil {
		return x.CpuLoad
	}
	return 0
}

func (x *Node) GetMemLoad() float64 {
	if x != nil {
		return x.MemLoad
	}
	return 0
}

func (x *Node) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreatePodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *PodSpec               `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePodRequest) Reset() {
	*x = CreatePodRequest{}
	mi := &file_proto_minik8s_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePodRequest) ProtoMessage() {}

func (x *CreatePodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_minik8s_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePodRequest.ProtoReflect.Descriptor instead.
func (*CreatePodRequest) Descriptor() ([]byte, []int) {
	return file_proto_minik8s_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePodRequest) GetSpec() *PodSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type CreatePodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pod           *Pod                   `protobuf:"bytes,1,opt,name=pod,proto3" json:"pod,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePodResponse) Reset() {
	*x = CreatePodResponse{}
	mi := &file_proto_minik8s_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePodResponse) ProtoMessage() {}

func (x *CreatePodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_minik8s_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePodResponse.ProtoReflect.Descriptor instead.
func (*CreatePodResponse) Descriptor() ([]byte, []int) {
	return file_proto_minik8s_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePodResponse) GetPod() *Pod {
	if x != nil {
		return x.Pod
	}
	return nil
}

type ListPodsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPodsRequest) Reset() {
	*x = ListPodsRequest{}
	mi := &file_proto_minik8s_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPodsRequest) ProtoMessage() {}

func (x *ListPodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_minik8s_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPodsRequest.ProtoReflect.Descriptor instead.
func (*ListPodsRequest) Descriptor() ([]byte, []int) {
	return file_proto_minik8s_proto_rawDescGZIP(), []int{5}
}

type ListPodsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pods          []*Pod                 `protobuf:"bytes,1,rep,name=pods,proto3" json:"pods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPodsResponse) Reset() {
	*x = ListPodsResponse{}
	mi := &file_proto_minik8s_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPodsResponse) ProtoMessage() {}

func (x *ListPodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_minik8s_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPodsResponse.ProtoReflect.Descriptor instead.
func (*ListPodsResponse) Descriptor() ([]byte, []int) {
	return file_proto_minik8s_proto_rawDescGZIP(), []int{6}
}

func (x *ListPodsResponse) GetPods() []*Pod {
	if x != nil {
		return x.Pods
	}
	return nil
}

type RegisterNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_proto_minik8s_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_minik8s_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_minik8s_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterNodeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RegisterNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *Node                  `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_proto_minik8s_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_minik8s_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_minik8s_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterNodeResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Cpu           float64                `protobuf:"fixed64,2,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        float64                `protobuf:"fixed64,3,opt,name=memory,proto3" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_minik8s_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_minik8s_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_minik8s_proto_rawDescGZIP(), []int{9}
}

func (x *HeartbeatRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HeartbeatRequest) GetCpu() float64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *HeartbeatRequest) GetMemory() float64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_minik8s_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_minik8s_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_minik8s_proto_rawDescGZIP(), []int{10}
}

var File_proto_minik8s_proto protoreflect.FileDescriptor

const file_proto_minik8s_proto_rawDesc = "" +
	"\n" +
	"\x13proto/minik8s.proto\x12\x05proto\"E\n" +
	"\aPodSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x10\n" +
	"\x03cmd\x18\x03 \x03(\tR\x03cmd\"n\n" +
	"\x03Pod\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\x04spec\x18\x02 \x01(\v2\x0e.proto.PodSpecR\x04spec\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1b\n" +
	"\tnode_name\x18\x04 \x01(\tR\bnodeName\"h\n" +
	"\x04Node\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bcpu_load\x18\x02 \x01(\x01R\acpuLoad\x12\x19\n" +
	"\bmem_load\x18\x03 \x01(\x01R\amemLoad\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"6\n" +
	"\x10CreatePodRequest\x12\"\n" +
	"\x04spec\x18\x01 \x01(\v2\x0e.proto.PodSpecR\x04spec\"1\n" +
	"\x11CreatePodResponse\x12\x1c\n" +
	"\x03pod\x18\x01 \x01(\v2\n" +
	".proto.PodR\x03pod\"\x11\n" +
	"\x0fListPodsRequest\"2\n" +
	"\x10ListPodsResponse\x12\x1e\n" +
	"\x04pods\x18\x01 \x03(\v2\n" +
	".proto.PodR\x04pods\")\n" +
	"\x13RegisterNodeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"7\n" +
	"\x14RegisterNodeResponse\x12\x1f\n" +
	"\x04node\x18\x01 \x01(\v2\v.proto.NodeR\x04node\"P\n" +
	"\x10HeartbeatRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03cpu\x18\x02 \x01(\x01R\x03cpu\x12\x16\n" +
	"\x06memory\x18\x03 \x01(\x01R\x06memory\"\x13\n" +
	"\x11HeartbeatResponse2\x91\x02\n" +
	"\tApiServer\x12>\n" +
	"\tCreatePod\x12\x17.proto.CreatePodRequest\x1a\x18.proto.CreatePodResponse\x12;\n" +
	"\bListPods\x12\x16.proto.ListPodsRequest\x1a\x17.proto.ListPodsResponse\x12G\n" +
	"\fRegisterNode\x12\x1a.proto.RegisterNodeRequest\x1a\x1b.proto.RegisterNodeResponse\x12>\n" +
	"\tHeartbeat\x12\x17.proto.HeartbeatRequest\x1a\x18.proto.HeartbeatResponseB\x0fZ\rminik8s/protob\x06proto3"

var (
	file_proto_minik8s_proto_rawDescOnce sync.Once
	file_proto_minik8s_proto_rawDescData []byte
)

func file_proto_minik8s_proto_rawDescGZIP() []byte {
	file_proto_minik8s_proto_rawDescOnce.Do(func() {
		file_proto_minik8s_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_minik8s_proto_rawDesc), len(file_proto_minik8s_proto_rawDesc)))
	})
	return file_proto_minik8s_proto_rawDescData
}

var file_proto_minik8s_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_minik8s_proto_goTypes = []any{
	(*PodSpec)(nil),              // 0: proto.PodSpec
	(*Pod)(nil),                  // 1: proto.Pod
	(*Node)(nil),                 // 2: proto.Node
	(*CreatePodRequest)(nil),     // 3: proto.CreatePodRequest
	(*CreatePodResponse)(nil),    // 4: proto.CreatePodResponse
	(*ListPodsRequest)(nil),      // 5: proto.ListPodsRequest
	(*ListPodsResponse)(nil),     // 6: proto.ListPodsResponse
	(*RegisterNodeRequest)(nil),  // 7: proto.RegisterNodeRequest
	(*RegisterNodeResponse)(nil), // 8: proto.RegisterNodeResponse
	(*HeartbeatRequest)(nil),     // 9: proto.HeartbeatRequest
	(*HeartbeatResponse)(nil),    // 10: proto.HeartbeatResponse
}
var file_proto_minik8s_proto_depIdxs = []int32{
	0,  // 0: proto.Pod.spec:type_name -> proto.PodSpec
	0,  // 1: proto.CreatePodRequest.spec:type_name -> proto.PodSpec
	1,  // 2: proto.CreatePodResponse.pod:type_name -> proto.Pod
	1,  // 3: proto.ListPodsResponse.pods:type_name -> proto.Pod
	2,  // 4: proto.RegisterNodeResponse.node:type_name -> proto.Node
	3,  // 5: proto.ApiServer.CreatePod:input_type -> proto.CreatePodRequest
	5,  // 6: proto.ApiServer.ListPods:input_type -> proto.ListPodsRequest
	7,  // 7: proto.ApiServer.RegisterNode:input_type -> proto.RegisterNodeRequest
	9,  // 8: proto.ApiServer.Heartbeat:input_type -> proto.HeartbeatRequest
	4,  // 9: proto.ApiServer.CreatePod:output_type -> proto.CreatePodResponse
	6,  // 10: proto.ApiServer.ListPods:output_type -> proto.ListPodsResponse
	8,  // 11: proto.ApiServer.RegisterNode:output_type -> proto.RegisterNodeResponse
	10, // 12: proto.ApiServer.Heartbeat:output_type -> proto.HeartbeatResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_minik8s_proto_init() }
func file_proto_minik8s_proto_init() {
	if File_proto_minik8s_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_minik8s_proto_rawDesc), len(file_proto_minik8s_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_minik8s_proto_goTypes,
		DependencyIndexes: file_proto_minik8s_proto_depIdxs,
		MessageInfos:      file_proto_minik8s_proto_msgTypes,
	}.Build()
	File_proto_minik8s_proto = out.File
	file_proto_minik8s_proto_goTypes = nil
	file_proto_minik8s_proto_depIdxs = nil
}
